### ISSUE TITLE
Prevalence class box multiplicates when scrolling down the page - see image

### ISSUE THREAD

**Issue by tudorgroza** [Bio-LarK/orpha#103]
![screen shot 2015-02-09 at 2 13 00 pm](https://cloud.githubusercontent.com/assets/1421201/6100548/cf215018-b065-11e4-874b-7863e360f61c.png)

**Comment by tudorgroza** [comment]
Silly me ... I forgot that it takes multiple sets of values.

**Comment by cmcnamara87** [comment]
Haha all good. Probably need to work out a better way to show it, but it was the easiest way to get it all in there for now.
