### ISSUE TITLE
edit properties on disorder

### ISSUE THREAD

**Issue by cmcnamara87** [Bio-LarK/orpha#109]
Edit and delete
- [x] type of inheritance
- [x] age of onset
- [x] age of death
- [x] disorder type

**Comment by cmcnamara87** [comment]
@tudorgroza for the Disorder type, can it be multiple values?

**Comment by tudorgroza** [comment]
No - a single value.

**Comment by cmcnamara87** [comment]
You should be able to edit the type of inheritance, age of onset and age of death. Working on disorder type now.

**Comment by tudorgroza** [comment]
There are no properties ...

![screen shot 2015-02-19 at 3 20 44 pm](https://cloud.githubusercontent.com/assets/1421201/6261840/c526ba8e-b84a-11e4-86ea-b848f5f05abd.png)

**Comment by cmcnamara87** [comment]
Give it a refresh, should be working now

**Comment by tudorgroza** [comment]
Looks perfect.
There is a small bug - the first time you open the autocompletion box, you can add again a value that is already pre-populated. However, once you add it, then the value is no longer available. See screenshot.

![screen shot 2015-02-19 at 4 25 05 pm](https://cloud.githubusercontent.com/assets/1421201/6262256/cf5dac84-b853-11e4-8289-35bd296569fa.png)

**Comment by cmcnamara87** [comment]
See #119 for the dropdown bug

**Comment by cmcnamara87** [comment]
Okay done for the disorder type as well. Let me know if it works.
