### ISSUE TITLE
edit gene relationship (check this works)

### ISSUE THREAD

**Issue by cmcnamara87** [Bio-LarK/orpha#110]

**Comment by tudorgroza** [comment]
The relations seem to work, but the gene name bug appears again - see screenshot.
In 'View' mode the gene names are present - in 'Edit' mode the switch back to _NO_NAME_. This is then transported to the modal edit window.

![screen shot 2015-02-19 at 8 32 33 pm](https://cloud.githubusercontent.com/assets/1421201/6264269/848fd880-b876-11e4-8ad1-8e7166d8e356.png)

**Comment by cmcnamara87** [comment]
Yep this is probably going to keep cropping up, it will be fixed if we re-import the data with that fix you applied. I'll try and see if I can fix it further up the chain, because its occuring so many places.
