### ISSUE TITLE
pull prevalence class out of box, into its own box

### ISSUE THREAD

**Issue by cmcnamara87** [Bio-LarK/orpha#99]

**Comment by cmcnamara87** [comment]
@tudorgroza  I've pulled it out, I think I will have to move some of the other stuff around, because the prevalence box can be very long.

![screen shot 2015-02-06 at 12 08 58 pm](https://cloud.githubusercontent.com/assets/639134/6073369/16cd2de8-adf9-11e4-90b6-a8942cf2cf17.png)

**Comment by tudorgroza** [comment]
How about if you make it a line similar to what you have now on top of the description. Something like a bigger box with the heading 'Prevalence class' and then on each line:

Valmoy   Validation   Qualification   Geography    Class           Type                     Source
0.0           Validated   Class only      Worldwide    <1 / 100000  Point prevalence  PMID: ...
